# Generated by Django 2.2.6 on 2020-03-17 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '0005_auto_20200317_1758'),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permission',
            options={'ordering': ('department', 'content_type__app_label', 'content_type__model', 'codename'), 'verbose_name': 'permission', 'verbose_name_plural': 'permissions'},
        ),
        migrations.AddField(
            model_name='permission',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.Department'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='permission',
            unique_together={('content_type', 'codename', 'department')},
        ),
    ]
